### ISSUE TITLE
Removing the laptop's bottom case

### ISSUE THREAD

**Issue by dkoluris** [ongengi/HP-ENVY-13-AH0004TU-Hackintosh-OpenCore#1]
Hello :) I hope you are doing fine. Did you have any problem removing the bottom case of the laptop, and also being able to re-attach the rubber legs of it properly? Best regards.

**Comment by ongengi** [comment]
> attach

This video demonstrates how to remove the bottom case of the laptop, hope it is useful to you, link:[HP ENVY 13-ah0026TX (MX150 獨顯版) 拆機更換SSD (2018.06)](https://www.youtube.com/watch?v=9OaYPK9CmV4&t=289s)

**Comment by ongengi** [comment]
> Hello :) I hope you are doing fine. Did you have any problem removing the bottom case of the laptop, and also being able to re-attach the rubber legs of it properly? Best regards.

Important: Do not open the screen until all screws are installed, otherwise the shaft will be damaged.

**Comment by dkoluris** [comment]
Thanks so much!
